# -----------------------------------------------------------------------------------------------
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

# -----------------------------------------------------------------------------------------------
'''
此题的关键点：
字符串的replace()函数是全部对符合条件的字符进行替换，所以对于'a'和'aa'这样的测试数据
就不能ac，所以就要将字符串先转化为列表，利用列表的remove()单一的进行删除，再转回字符串格式

此题虽然ac，但是Runtime: 105 ms
所以还需要进行优化
'''
# -----------------------------------------------------------------------------------------------
# class Solution(object):
#     def findTheDifference(self, s, t):
#         """
#         :type s: str
#         :type t: str
#         :rtype: str
#         """
#         list_t = list(t)
#         list_s = list(s)
#         for x in list_s:
#             list_t.remove(x)
#         return (''.join(list_t))

# print(findTheDifference("dragon","dragony"))
# print(findTheDifference("a","aa"))
# -----------------------------------------------------------------------------------------------

# -----------------------------------------Best Result-------------------------------------------
'''
#1-liners and 2-liner in Python
#Using XOR:

class Solution(object):
    def findTheDifference(self, s, t):
        return chr(reduce(operator.xor, map(ord, s + t)))

#Using collections.Counter():

class Solution(object):
    def findTheDifference(self, s, t):
        return list((collections.Counter(t) - collections.Counter(s)))[0]

#A 2-liner here using sorted():

class Solution(object):
    def findTheDifference(self, s, t):
        s, t = sorted(s), sorted(t)
        return t[-1] if s == t[:-1] else [x[1] for x in zip(s, t) if x[0] != x[1]][0]
'''
# ------------------------------------------------------------------------------------------------


# --------------------------------------------草稿-------------------------------------------------
import collections
def findTheDifference(s, t):
#     list_t = list(t)
#     list_s = list(s)
#     for x in list_s:
#         list_t.remove(x)
#     return (''.join(list_t))

    # return (list((collections.Counter(t) - collections.Counter(s)))[0])
    return list(collections.Counter(t) - collections.Counter(s))

print(findTheDifference("dragon","dragony"))
print(findTheDifference("a","aa"))

# lis1 = ['a', 'a', 'b']
# lis1.remove('a')
# print(lis1)

# L = 'aa'
# list_L = list(L)
# S = 'a'
# list_S = list(S)
# for x in list_S:
#     list_L.remove(x)
# print(''.join(list_L))

# -----------------------------------------------------------------------------------------------
